### ISSUE TITLE
Alternate language validators

### ISSUE THREAD

**Issue by MikeMcQuaid** [sxtxixtxcxh/validate-on-save.tmbundle#27]
I ❤️ this bundle, thanks for it.

I'm thinking of adding a Rubocop validator for Ruby and `shellcheck` validator for Bash. Any thoughts on what the best way would be to implement these given they require external dependencies and not everyone may want to use them? A separate validator? A validator that people enable optionally?

Thanks!

**Comment by claylo** [comment]
@MikeMcQuaid I'm a contributor/maintainer as well, and I agree that a more modular structure (similar to how the Atom guys have done theirs) would be beneficial.

**Comment by MikeMcQuaid** [comment]
I'm not critiquing the current structure, for what it's worth, just wondering how to structure any PR/work on this so as to best get accepted.

**Comment by MikeMcQuaid** [comment]
Closing in favour of PR in #28.
